version: 2.1
orbs:
  allure: ayte/allure@0.1.3
jobs:
  build:
    docker:
      - image: "circleci/openjdk:11-jdk"
    environment:
      MAVEN_OPTS: "-Xmx3200m"
    working_directory: ~/repo
    steps:
      - checkout

      - allure/install

      - restore_cache:
          keys:
            - maven-dependencies-{{ checksum "pom.xml" }}
            - maven-dependencies-

      - save_cache:
          key: maven-dependencies-{{ checksum "pom.xml" }}
          paths:
            - ~/.m2

      - run: mvn test

      - allure/report

      - store_test_results:
          path: ~/repo/target/surefire-reports/API_Testing
